# ref: https://github.com/azu/textlint-reviewdog-example
version: 2.1

jobs:
  proofreading_job:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install textlint"
          command: npm install --save-dev textlint textlint-rule-common-misspellings
      - run:    
          name: "Install dependent module"
          command: npm install
      - run:
          name: "Install reviewdog"
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
      - run: # (d1)
          name: "Execute textlint for README.md"
          command: npx textlint --rule common-misspellings README.md >> .textlint.log
                   
      - run: # (d2)
          name: "Execute reviewdog"
          when: on_fail
          environment:
            CIRCLE_PR_NUMBER: 5
          command: |
            cat .textlint.log | ./bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
workflows:
  version: 2
  proofreading:
    jobs:
      - proofreading_job
